Dear Participant,

Please find below the Project for Statistical Learning course. This is an individual assignment. Kindly submit it before it's deadline.

The Titan Insurance Company has just installed a new incentive payment scheme for its lift policy sales force. It wants to have an early view of the success or failure of the new scheme. Indications are that the sales force is selling more policies, but sales always vary in an unpredictable pattern from month to month and it is not clear that the scheme has made a significant difference.

Life Insurance companies typically measure the monthly output of a salesperson as the total sum assured for the policies sold by that person during the month. For example, suppose salesperson X has, in the month, sold seven policies for which the sums assured are £1000, £2500, £3000, £5000, £10000, £35000. X's output for the month is the total of these sums assured, £61,500. Titan's new scheme is that the sales force receives low regular salaries but are paid large bonuses related to their output (i.e. to the total sum assured of policies sold by them). The scheme is expensive for the company, but they are looking for sales increases which more than compensate. The agreement with the sales force is that if the scheme does not at least break even for the company, it will be abandoned after six months.

The scheme has now been in operation for four months. It has settled down after fluctuations in the first two months due to the changeover.

To test the effectiveness of the scheme, Titan have taken a random sample of 30 salespeople measured their output in the penultimate month prior to changeover and then measured it in the fourth month after the changeover (they have deliberately chosen months not too close to the changeover). The outputs of the salespeople are shown in data.csv

In [2]:
# Load the necessary packages

import numpy as np
import pandas as pd
import scipy.stats as stats
import matplotlib.pyplot as plt

In [17]:
# Import Data 
mydata = pd.read_csv('data_TitanInsurance.csv')

In [90]:
mydata.head()

   SALESPERSON  Old Scheme (in thousands)  New Scheme (in thousands)
0            1                         57                         62
1            2                        103                        122
2            3                         59                         54
3            4                         75                         82
4            5                         84                         84

1. Find the mean of old scheme and new scheme column. (5 points)

In [43]:
#Ans1
np.mean(mydata)

SALESPERSON                  15.500000
Old Scheme (in thousands)    68.033333
New Scheme (in thousands)    72.033333
dtype: float64

2. Use the five percent significance test over the data to determine the p value to check new scheme has significantly raised outputs? (10 points)

In [44]:
#Ans2
from scipy.stats import ttest_1samp, ttest_ind, mannwhitneyu, levene, shapiro,wilcoxon
from statsmodels.stats.power import ttest_power

#Null Hypothesis : The new scheme has significantly  raised the output
#Alternate Hypothesis : The new scheme is not significantly raised the output

In [91]:
group1 = mydata.iloc[:,1:-1]
group2 = mydata.iloc[:,2:]

In [92]:
group2.head()

   New Scheme (in thousands)
0                         62
1                        122
2                         54
3                         82
4                         84

In [93]:
t_statistic, p_value = ttest_ind(group1, group2)
print("The T Values is = ",t_statistic,",  The p Values is = ", p_value)

The T Values is =  [-0.69370676] ,  The p Values is =  [0.49063516]

Ans3

Conclusion : P value is 0.49 which is greater than 0.05 hence we accept the NULL Hypothesis i.e The new scheme has significantly  raised the output

Ques 4. Suppose it has been calculated that in order for Titan to break even, the average output must increase by £5000 in the scheme compared to the old scheme. If this figure is alternative hypothesis, what is:

        a) The probability of a type 1 error? (2.5 points)

        b) What is the p- value of the hypothesis test if we test for a difference of $5000? (5 points)

        c) Power of the test (5 points)

#NULL Hypothesis - the average output increased by £5000 
#Alternative Hypothesis test - The average output has not increased by £5000

In [ ]:
#a) The probability of a type 1 error? (2.5 points)

#Ans - Probabilty of Type 1 error is 5% or 0.05

In [81]:
#b) What is the p- value of the hypothesis test if we test for a difference of $5000?
mydatadiff = mydata['New Scheme (in thousands)']- mydata['Old Scheme (in thousands)']

In [82]:

mydatadiff
#Assuming the data is not normally distributed using Z Statistic - Wilcoxon

0      5
1     19
2     -5
3      7
4      0
5     13
6     -3
7     -6
8     -6
9     25
10    17
11    21
12    21
13   -14
14    -7
15    19
16    -7
17   -34
18    -7
19    13
20    13
21     9
22   -11
23    11
24    18
25   -19
26     8
27    -7
28     9
29    18
dtype: int64

In [94]:
z_statistic, p_value = wilcoxon(mydatadiff - 5)
print ("The p- value is for hypothesis test for a difference of $5K is ", p_value)

The p- value is for hypothesis test for a difference of $5K is  0.9482203719337259

In [95]:
#c) Power of the test
(np.mean(mydatadiff) - 5) / np.std(mydatadiff)

-0.07223151185146152

In [97]:
print("Power of test is :",ttest_power(-0.072, nobs=30, alpha=0.05))

Power of test is : 0.06683060529539009