## Linear Classifier in TensorFlow 
Using Low Level API in Eager Execution mode

### Load tensorflow

In [0]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
import numpy as np
tf.enable_eager_execution()

### Collect Data

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
import pandas as pd

In [0]:
df1 = pd.read_csv("/content/drive/My Drive/prices.csv")

### Check all columns in the dataset

In [6]:
df1.head()

                  date symbol        open  ...         low        high     volume
0  2016-01-05 00:00:00   WLTW  123.430000  ...  122.309998  126.250000  2163600.0
1  2016-01-06 00:00:00   WLTW  125.239998  ...  119.940002  125.540001  2386400.0
2  2016-01-07 00:00:00   WLTW  116.379997  ...  114.930000  119.739998  2489500.0
3  2016-01-08 00:00:00   WLTW  115.480003  ...  113.500000  117.440002  2006300.0
4  2016-01-11 00:00:00   WLTW  117.010002  ...  114.089996  117.330002  1408600.0

[5 rows x 7 columns]

### Drop columns `date` and  `symbol`

In [0]:
df1 = df1.drop(['date', 'symbol'], axis = 1)

In [8]:
df1.head()

         open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

In [9]:
df1.shape

(851264, 5)

### Consider only first 1000 rows in the dataset for building feature set and target set
Target 'Volume' has very high values. Divide 'Volume' by 1000,000

In [0]:
df1t = df1[:1000]

In [11]:
df1t.shape

(1000, 5)

### Divide the data into train and test sets

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
# split into input (X) and output (Y) variables
X = df1t.iloc[:,0:4]
Y = df1t.iloc[:,[4]]
#split into 67% for train and 33% for test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=7)

In [14]:
# split into input (X) and output (Y) variables
print(X.head())

print(Y.head())

         open       close         low        high
0  123.430000  125.839996  122.309998  126.250000
1  125.239998  119.980003  119.940002  125.540001
2  116.379997  114.949997  114.930000  119.739998
3  115.480003  116.620003  113.500000  117.440002
4  117.010002  114.970001  114.089996  117.330002
      volume
0  2163600.0
1  2386400.0
2  2489500.0
3  2006300.0
4  1408600.0

#### Convert Training and Test Data to numpy float32 arrays

In [0]:
import numpy as np

In [0]:
X_train = np.float32(X_train)
X_test = np.float32(X_test)
y_train = np.float32(y_train)
y_test= np.float32(y_test)

### Normalize the data
You can use Normalizer from sklearn.preprocessing

In [0]:
from sklearn.preprocessing import normalize

X_train = normalize(np.vstack([X_train]), norm='l2', axis=1)
X_test = normalize(np.vstack([X_test]), norm='l2', axis=1)

## Building the Model in tensorflow

1.Define Weights and Bias, use tf.zeros to initialize weights and Bias

In [0]:
W = tf.random_normal(shape=[4,1])
b = tf.zeros(shape=[1])

In [19]:
import tensorflow as tf
W.numpy()

array([[ 1.9677166 ],
       [ 2.1858313 ],
       [ 0.78383625],
       [-0.5629888 ]], dtype=float32)

2.Define a function to calculate prediction

In [0]:
y = tf.add(tf.matmul(X_train,W),b,name='output')

3.Loss (Cost) Function [Mean square error]

In [21]:
loss = tf.reduce_mean(tf.square(y_train-y),name='Loss')
loss

4.Function to train the Model

1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
train_op = tf.train.GradientDescentOptimizer(0.03)

In [23]:
W

<tf.Tensor: id=5, shape=(4, 1), dtype=float32, numpy=
array([[ 1.9677166 ],
       [ 2.1858313 ],
       [ 0.78383625],
       [-0.5629888 ]], dtype=float32)>

In [24]:
b

In [25]:
train_op

In [0]:
#how many times data need to be shown to model
training_epochs = 100

In [0]:
def loss(X_train,y_train,W,b):
  yPred = tf.add(tf.matmul(X_train,W),b)
  return tf.reduce_mean(tf.square(y_train-yPred))

In [0]:
def training(X,W,b,y,learning_value):
    with tf.GradientTape() as t:
       t.watch([W,b])
       loss1 = loss(X,y,W,b)
    dw,db=t.gradient(loss1,[W,b])
    w=W-learning_value*dw
    b=b-learning_value*db
    return w,b

## Train the model for 100 epochs 
1. Observe the training loss at every iteration
2. Observe Train loss at every 5th iteration

In [30]:
for epoch in range(training_epochs):
            
#     #Calculate train_op and loss
#     _, train_loss = sess.run([train_op,loss],{x:X_train, y_:y_train})
    
#     if epoch % 5 == 0:
#         print ('Training loss at step: ', epoch, ' is ', train_loss)

    Wcalc,bcalc = training(X_train,W,b,y_train,0.3)
  
    if epoch % 5 == 0:
        print ('Training loss at step: ', epoch, ' is ', loss(X_train,y_train,Wcalc,bcalc).numpy())

Training loss at step:  0  is  286774900000000.0
Training loss at step:  5  is  286774900000000.0
Training loss at step:  10  is  286774900000000.0
Training loss at step:  15  is  286774900000000.0
Training loss at step:  20  is  286774900000000.0
Training loss at step:  25  is  286774900000000.0
Training loss at step:  30  is  286774900000000.0
Training loss at step:  35  is  286774900000000.0
Training loss at step:  40  is  286774900000000.0
Training loss at step:  45  is  286774900000000.0
Training loss at step:  50  is  286774900000000.0
Training loss at step:  55  is  286774900000000.0
Training loss at step:  60  is  286774900000000.0
Training loss at step:  65  is  286774900000000.0
Training loss at step:  70  is  286774900000000.0
Training loss at step:  75  is  286774900000000.0
Training loss at step:  80  is  286774900000000.0
Training loss at step:  85  is  286774900000000.0
Training loss at step:  90  is  286774900000000.0
Training loss at step:  95  is  286774900000000.0

### Get the shapes and values of W and b

In [31]:
W

<tf.Tensor: id=5, shape=(4, 1), dtype=float32, numpy=
array([[ 1.9677166 ],
       [ 2.1858313 ],
       [ 0.78383625],
       [-0.5629888 ]], dtype=float32)>

In [33]:
W.shape

TensorShape([Dimension(4), Dimension(1)])

In [34]:
b

In [35]:
b.shape

TensorShape([Dimension(1)])

### Model Prediction on 1st Examples in Test Dataset

In [0]:
def predict(x,w,b):
    return tf.add(tf.matmul(x,w),b)
  
y_predict = predict(X_test[0:1], W, b)

In [42]:
y_predict

## Classification using tf.Keras

In this exercise, we will build a Deep Neural Network using tf.Keras. We will use Iris Dataset for this exercise.

### Load the given Iris data using pandas (Iris.csv)

In [0]:
df = pd.read_csv("/content/drive/My Drive/Iris.csv")

In [262]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

In [0]:
df = pd.get_dummies(df['Species'])

In [264]:
df.head()

   Id  SepalLengthCm  ...  Species_Iris-versicolor  Species_Iris-virginica
0   1            5.1  ...                        0                       0
1   2            4.9  ...                        0                       0
2   3            4.7  ...                        0                       0
3   4            4.6  ...                        0                       0
4   5            5.0  ...                        0                       0

[5 rows x 8 columns]

### Splitting the data into feature set and target set

In [0]:
# split into input (X) and output (Y) variables
X = df.iloc[:,1:5]
#Y = df.iloc[:,6:9]
Y = df[["Species_Iris-setosa", "Species_Iris-versicolor", "Species_Iris-virginica"]]
#split into 67% for train and 33% for test
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.33, random_state=7)

In [286]:
X.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [289]:
Y.head()

   Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica
0                    1                        0                       0
1                    1                        0                       0
2                    1                        0                       0
3                    1                        0                       0
4                    1                        0                       0

In [290]:
X_test.head()

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
149            5.9           3.0            5.1           1.8
84             5.4           3.0            4.5           1.5
40             5.0           3.5            1.3           0.3
66             5.6           3.0            4.5           1.5
106            4.9           2.5            4.5           1.7

In [292]:
y_test.head()

     Species_Iris-setosa  Species_Iris-versicolor  Species_Iris-virginica
149                    0                        0                       1
84                     0                        1                       0
40                     1                        0                       0
66                     0                        1                       0
106                    0                        0                       1

###  Building Model in tf.keras

Build a Linear Classifier model  <br>
1.  Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3<br> 
2. Apply Softmax on Dense Layer outputs <br>
3. Use SGD as Optimizer
4. Use categorical_crossentropy as loss function

In [0]:
import numpy
from pandas import read_csv
from keras.models import Sequential
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D
from keras.layers import Flatten
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [0]:
# create model
model = tf.keras.Sequential()
#model.add(Dense(2, input_dim=4, activation='relu')) 
model.add(tf.keras.layers.Dense(3, input_shape=(4,),activation='softmax')) # Output layer 
# Compile model
model.compile(loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
# there are 2 cross Entorpy - Binary_crossentrophu for binary class model for Multiple class- Categorical class entrophy
# Classification use Entorphy and for Regression use mse 
#optimizer  in next class
# Metric = Accuracy

### Model Training

In [295]:
model.fit(X_train, y_train, validation_data=(X_test,y_test), epochs=200)

Train on 100 samples, validate on 50 samples
Epoch 1/200
100/100 [==============================] - 0s 2ms/sample - loss: 2.0126 - acc: 0.4800 - val_loss: 1.8471 - val_acc: 0.6400
Epoch 2/200
100/100 [==============================] - 0s 235us/sample - loss: 1.5109 - acc: 0.6800 - val_loss: 1.4620 - val_acc: 0.6400
Epoch 3/200
100/100 [==============================] - 0s 212us/sample - loss: 1.2076 - acc: 0.6800 - val_loss: 1.1421 - val_acc: 0.6400
Epoch 4/200
100/100 [==============================] - 0s 173us/sample - loss: 0.9735 - acc: 0.6800 - val_loss: 0.9348 - val_acc: 0.3600
Epoch 5/200
100/100 [==============================] - 0s 186us/sample - loss: 0.8608 - acc: 0.4900 - val_loss: 0.9240 - val_acc: 0.5800
Epoch 6/200
100/100 [==============================] - 0s 180us/sample - loss: 0.8404 - acc: 0.5300 - val_loss: 0.9539 - val_acc: 0.6400
Epoch 7/200
100/100 [==============================] - 0s 280us/sample - loss: 0.8494 - acc: 0.6600 - val_loss: 0.8714 - val_acc: 0.4000
Epoch 8/200
100/100 [==============================] - 0s 179us/sample - loss: 0.8034 - acc: 0.4800 - val_loss: 0.8556 - val_acc: 0.3200
Epoch 9/200
100/100 [==============================] - 0s 166us/sample - loss: 0.7953 - acc: 0.3900 - val_loss: 0.8527 - val_acc: 0.3800
Epoch 10/200
100/100 [==============================] - 0s 215us/sample - loss: 0.7953 - acc: 0.4300 - val_loss: 0.8332 - val_acc: 0.3600
Epoch 11/200
100/100 [==============================] - 0s 196us/sample - loss: 0.7791 - acc: 0.4200 - val_loss: 0.8308 - val_acc: 0.4600
Epoch 12/200
100/100 [==============================] - 0s 197us/sample - loss: 0.7700 - acc: 0.4700 - val_loss: 0.8310 - val_acc: 0.5400
Epoch 13/200
100/100 [==============================] - 0s 204us/sample - loss: 0.7657 - acc: 0.5100 - val_loss: 0.8432 - val_acc: 0.6200
Epoch 14/200
100/100 [==============================] - 0s 203us/sample - loss: 0.7672 - acc: 0.6200 - val_loss: 0.8137 - val_acc: 0.5400
Epoch 15/200
100/100 [==============================] - 0s 189us/sample - loss: 0.7647 - acc: 0.5100 - val_loss: 0.7962 - val_acc: 0.3600
Epoch 16/200
100/100 [==============================] - 0s 181us/sample - loss: 0.7468 - acc: 0.3800 - val_loss: 0.7966 - val_acc: 0.3800
Epoch 17/200
100/100 [==============================] - 0s 183us/sample - loss: 0.7389 - acc: 0.4600 - val_loss: 0.7875 - val_acc: 0.3600
Epoch 18/200
100/100 [==============================] - 0s 176us/sample - loss: 0.7277 - acc: 0.4600 - val_loss: 0.8040 - val_acc: 0.6000
Epoch 19/200
100/100 [==============================] - 0s 183us/sample - loss: 0.7327 - acc: 0.5900 - val_loss: 0.7998 - val_acc: 0.6200
Epoch 20/200
100/100 [==============================] - 0s 190us/sample - loss: 0.7257 - acc: 0.6300 - val_loss: 0.7749 - val_acc: 0.4000
Epoch 21/200
100/100 [==============================] - 0s 192us/sample - loss: 0.7242 - acc: 0.4200 - val_loss: 0.7621 - val_acc: 0.3600
Epoch 22/200
100/100 [==============================] - 0s 239us/sample - loss: 0.7116 - acc: 0.4100 - val_loss: 0.7845 - val_acc: 0.5400
Epoch 23/200
100/100 [==============================] - 0s 194us/sample - loss: 0.7256 - acc: 0.5400 - val_loss: 0.7547 - val_acc: 0.4000
Epoch 24/200
100/100 [==============================] - 0s 167us/sample - loss: 0.7022 - acc: 0.4400 - val_loss: 0.7435 - val_acc: 0.3800
Epoch 25/200
100/100 [==============================] - 0s 198us/sample - loss: 0.6899 - acc: 0.4700 - val_loss: 0.7426 - val_acc: 0.5200
Epoch 26/200
100/100 [==============================] - 0s 179us/sample - loss: 0.6838 - acc: 0.5300 - val_loss: 0.7330 - val_acc: 0.3600
Epoch 27/200
100/100 [==============================] - 0s 165us/sample - loss: 0.6775 - acc: 0.4500 - val_loss: 0.7312 - val_acc: 0.3400
Epoch 28/200
100/100 [==============================] - 0s 186us/sample - loss: 0.6759 - acc: 0.4000 - val_loss: 0.7249 - val_acc: 0.3600
Epoch 29/200
100/100 [==============================] - 0s 206us/sample - loss: 0.6736 - acc: 0.4900 - val_loss: 0.7201 - val_acc: 0.3600
Epoch 30/200
100/100 [==============================] - 0s 159us/sample - loss: 0.6627 - acc: 0.4400 - val_loss: 0.7251 - val_acc: 0.6000
Epoch 31/200
100/100 [==============================] - 0s 185us/sample - loss: 0.6629 - acc: 0.5800 - val_loss: 0.7207 - val_acc: 0.6000
Epoch 32/200
100/100 [==============================] - 0s 173us/sample - loss: 0.6582 - acc: 0.5600 - val_loss: 0.7086 - val_acc: 0.5000
Epoch 33/200
100/100 [==============================] - 0s 185us/sample - loss: 0.6508 - acc: 0.5400 - val_loss: 0.7110 - val_acc: 0.4200
Epoch 34/200
100/100 [==============================] - 0s 194us/sample - loss: 0.6565 - acc: 0.3800 - val_loss: 0.6966 - val_acc: 0.3400
Epoch 35/200
100/100 [==============================] - 0s 182us/sample - loss: 0.6531 - acc: 0.4000 - val_loss: 0.6945 - val_acc: 0.5000
Epoch 36/200
100/100 [==============================] - 0s 381us/sample - loss: 0.6434 - acc: 0.4400 - val_loss: 0.7374 - val_acc: 0.6400
Epoch 37/200
100/100 [==============================] - 0s 264us/sample - loss: 0.6546 - acc: 0.6800 - val_loss: 0.6984 - val_acc: 0.6200
Epoch 38/200
100/100 [==============================] - 0s 180us/sample - loss: 0.6343 - acc: 0.6300 - val_loss: 0.6804 - val_acc: 0.3600
Epoch 39/200
100/100 [==============================] - 0s 184us/sample - loss: 0.6332 - acc: 0.4400 - val_loss: 0.6771 - val_acc: 0.3800
Epoch 40/200
100/100 [==============================] - 0s 175us/sample - loss: 0.6246 - acc: 0.4900 - val_loss: 0.6781 - val_acc: 0.5800
Epoch 41/200
100/100 [==============================] - 0s 166us/sample - loss: 0.6285 - acc: 0.5000 - val_loss: 0.6849 - val_acc: 0.6400
Epoch 42/200
100/100 [==============================] - 0s 212us/sample - loss: 0.6303 - acc: 0.5700 - val_loss: 0.7466 - val_acc: 0.6400
Epoch 43/200
100/100 [==============================] - 0s 174us/sample - loss: 0.6483 - acc: 0.6800 - val_loss: 0.6786 - val_acc: 0.6400
Epoch 44/200
100/100 [==============================] - 0s 179us/sample - loss: 0.6115 - acc: 0.6700 - val_loss: 0.6687 - val_acc: 0.4200
Epoch 45/200
100/100 [==============================] - 0s 178us/sample - loss: 0.6123 - acc: 0.4700 - val_loss: 0.6557 - val_acc: 0.3800
Epoch 46/200
100/100 [==============================] - 0s 189us/sample - loss: 0.6044 - acc: 0.4300 - val_loss: 0.6543 - val_acc: 0.3600
Epoch 47/200
100/100 [==============================] - 0s 182us/sample - loss: 0.6002 - acc: 0.4800 - val_loss: 0.6749 - val_acc: 0.6200
Epoch 48/200
100/100 [==============================] - 0s 178us/sample - loss: 0.6182 - acc: 0.5700 - val_loss: 0.6455 - val_acc: 0.3800
Epoch 49/200
100/100 [==============================] - 0s 187us/sample - loss: 0.5935 - acc: 0.4600 - val_loss: 0.6425 - val_acc: 0.3800
Epoch 50/200
100/100 [==============================] - 0s 194us/sample - loss: 0.5903 - acc: 0.4600 - val_loss: 0.6392 - val_acc: 0.4600
Epoch 51/200
100/100 [==============================] - 0s 207us/sample - loss: 0.5888 - acc: 0.5500 - val_loss: 0.6364 - val_acc: 0.3600
Epoch 52/200
100/100 [==============================] - 0s 193us/sample - loss: 0.5853 - acc: 0.4400 - val_loss: 0.6329 - val_acc: 0.3800
Epoch 53/200
100/100 [==============================] - 0s 216us/sample - loss: 0.5831 - acc: 0.4800 - val_loss: 0.6447 - val_acc: 0.6400
Epoch 54/200
100/100 [==============================] - 0s 191us/sample - loss: 0.5808 - acc: 0.6800 - val_loss: 0.6300 - val_acc: 0.4200
Epoch 55/200
100/100 [==============================] - 0s 174us/sample - loss: 0.5773 - acc: 0.4300 - val_loss: 0.6287 - val_acc: 0.4200
Epoch 56/200
100/100 [==============================] - 0s 179us/sample - loss: 0.5752 - acc: 0.4100 - val_loss: 0.6344 - val_acc: 0.6400
Epoch 57/200
100/100 [==============================] - 0s 178us/sample - loss: 0.5872 - acc: 0.6700 - val_loss: 0.6605 - val_acc: 0.6400
Epoch 58/200
100/100 [==============================] - 0s 187us/sample - loss: 0.5822 - acc: 0.6800 - val_loss: 0.6246 - val_acc: 0.6400
Epoch 59/200
100/100 [==============================] - 0s 185us/sample - loss: 0.5642 - acc: 0.6800 - val_loss: 0.6194 - val_acc: 0.6400
Epoch 60/200
100/100 [==============================] - 0s 178us/sample - loss: 0.5629 - acc: 0.6700 - val_loss: 0.6202 - val_acc: 0.6400
Epoch 61/200
100/100 [==============================] - 0s 181us/sample - loss: 0.5590 - acc: 0.6800 - val_loss: 0.6195 - val_acc: 0.6400
Epoch 62/200
100/100 [==============================] - 0s 182us/sample - loss: 0.5632 - acc: 0.6700 - val_loss: 0.6139 - val_acc: 0.4800
Epoch 63/200
100/100 [==============================] - 0s 183us/sample - loss: 0.5618 - acc: 0.4700 - val_loss: 0.6084 - val_acc: 0.4400
Epoch 64/200
100/100 [==============================] - 0s 181us/sample - loss: 0.5601 - acc: 0.5200 - val_loss: 0.6062 - val_acc: 0.4400
Epoch 65/200
100/100 [==============================] - 0s 173us/sample - loss: 0.5553 - acc: 0.4700 - val_loss: 0.6009 - val_acc: 0.4400
Epoch 66/200
100/100 [==============================] - 0s 166us/sample - loss: 0.5495 - acc: 0.5400 - val_loss: 0.5956 - val_acc: 0.4800
Epoch 67/200
100/100 [==============================] - 0s 194us/sample - loss: 0.5447 - acc: 0.5200 - val_loss: 0.5946 - val_acc: 0.3600
Epoch 68/200
100/100 [==============================] - 0s 201us/sample - loss: 0.5484 - acc: 0.5500 - val_loss: 0.5909 - val_acc: 0.4200
Epoch 69/200
100/100 [==============================] - 0s 186us/sample - loss: 0.5374 - acc: 0.5300 - val_loss: 0.5939 - val_acc: 0.6400
Epoch 70/200
100/100 [==============================] - 0s 187us/sample - loss: 0.5362 - acc: 0.6800 - val_loss: 0.5877 - val_acc: 0.6200
Epoch 71/200
100/100 [==============================] - 0s 179us/sample - loss: 0.5359 - acc: 0.6700 - val_loss: 0.5949 - val_acc: 0.6200
Epoch 72/200
100/100 [==============================] - 0s 172us/sample - loss: 0.5403 - acc: 0.5300 - val_loss: 0.5829 - val_acc: 0.4000
Epoch 73/200
100/100 [==============================] - 0s 217us/sample - loss: 0.5304 - acc: 0.5000 - val_loss: 0.5820 - val_acc: 0.4000
Epoch 74/200
100/100 [==============================] - 0s 214us/sample - loss: 0.5275 - acc: 0.5000 - val_loss: 0.5824 - val_acc: 0.6400
Epoch 75/200
100/100 [==============================] - 0s 193us/sample - loss: 0.5253 - acc: 0.6800 - val_loss: 0.5784 - val_acc: 0.6200
Epoch 76/200
100/100 [==============================] - 0s 185us/sample - loss: 0.5221 - acc: 0.6800 - val_loss: 0.5834 - val_acc: 0.6400
Epoch 77/200
100/100 [==============================] - 0s 178us/sample - loss: 0.5243 - acc: 0.6800 - val_loss: 0.5805 - val_acc: 0.6400
Epoch 78/200
100/100 [==============================] - 0s 182us/sample - loss: 0.5212 - acc: 0.6800 - val_loss: 0.5710 - val_acc: 0.6000
Epoch 79/200
100/100 [==============================] - 0s 180us/sample - loss: 0.5179 - acc: 0.6400 - val_loss: 0.5788 - val_acc: 0.6400
Epoch 80/200
100/100 [==============================] - 0s 193us/sample - loss: 0.5268 - acc: 0.5800 - val_loss: 0.5724 - val_acc: 0.6400
Epoch 81/200
100/100 [==============================] - 0s 181us/sample - loss: 0.5301 - acc: 0.5600 - val_loss: 0.5651 - val_acc: 0.6000
Epoch 82/200
100/100 [==============================] - 0s 229us/sample - loss: 0.5114 - acc: 0.5800 - val_loss: 0.5941 - val_acc: 0.6400
Epoch 83/200
100/100 [==============================] - 0s 178us/sample - loss: 0.5249 - acc: 0.6800 - val_loss: 0.5900 - val_acc: 0.6400
Epoch 84/200
100/100 [==============================] - 0s 190us/sample - loss: 0.5198 - acc: 0.6800 - val_loss: 0.5614 - val_acc: 0.6400
Epoch 85/200
100/100 [==============================] - 0s 188us/sample - loss: 0.5070 - acc: 0.6800 - val_loss: 0.5568 - val_acc: 0.6400
Epoch 86/200
100/100 [==============================] - 0s 211us/sample - loss: 0.5072 - acc: 0.5700 - val_loss: 0.5614 - val_acc: 0.6400
Epoch 87/200
100/100 [==============================] - 0s 343us/sample - loss: 0.5152 - acc: 0.6300 - val_loss: 0.5530 - val_acc: 0.7000
Epoch 88/200
100/100 [==============================] - 0s 172us/sample - loss: 0.5118 - acc: 0.6500 - val_loss: 0.5516 - val_acc: 0.6400
Epoch 89/200
100/100 [==============================] - 0s 181us/sample - loss: 0.4994 - acc: 0.6800 - val_loss: 0.5631 - val_acc: 0.6400
Epoch 90/200
100/100 [==============================] - 0s 212us/sample - loss: 0.5021 - acc: 0.6800 - val_loss: 0.5562 - val_acc: 0.6400
Epoch 91/200
100/100 [==============================] - 0s 173us/sample - loss: 0.4982 - acc: 0.6800 - val_loss: 0.5657 - val_acc: 0.6400
Epoch 92/200
100/100 [==============================] - 0s 248us/sample - loss: 0.5013 - acc: 0.6800 - val_loss: 0.5479 - val_acc: 0.6400
Epoch 93/200
100/100 [==============================] - 0s 220us/sample - loss: 0.4966 - acc: 0.6800 - val_loss: 0.5430 - val_acc: 0.6400
Epoch 94/200
100/100 [==============================] - 0s 196us/sample - loss: 0.4892 - acc: 0.6800 - val_loss: 0.5417 - val_acc: 0.6400
Epoch 95/200
100/100 [==============================] - 0s 195us/sample - loss: 0.4904 - acc: 0.6800 - val_loss: 0.5439 - val_acc: 0.6400
Epoch 96/200
100/100 [==============================] - 0s 239us/sample - loss: 0.4868 - acc: 0.6800 - val_loss: 0.5389 - val_acc: 0.6400
Epoch 97/200
100/100 [==============================] - 0s 203us/sample - loss: 0.4888 - acc: 0.6800 - val_loss: 0.5385 - val_acc: 0.6400
Epoch 98/200
100/100 [==============================] - 0s 198us/sample - loss: 0.4834 - acc: 0.6800 - val_loss: 0.5363 - val_acc: 0.6400
Epoch 99/200
100/100 [==============================] - 0s 207us/sample - loss: 0.4853 - acc: 0.7000 - val_loss: 0.5487 - val_acc: 0.6400
Epoch 100/200
100/100 [==============================] - 0s 199us/sample - loss: 0.4882 - acc: 0.6800 - val_loss: 0.5341 - val_acc: 0.6400
Epoch 101/200
100/100 [==============================] - 0s 201us/sample - loss: 0.4786 - acc: 0.6800 - val_loss: 0.5320 - val_acc: 0.6400
Epoch 102/200
100/100 [==============================] - 0s 206us/sample - loss: 0.4784 - acc: 0.6800 - val_loss: 0.5655 - val_acc: 0.6400
Epoch 103/200
100/100 [==============================] - 0s 202us/sample - loss: 0.5015 - acc: 0.6900 - val_loss: 0.5283 - val_acc: 0.8000
Epoch 104/200
100/100 [==============================] - 0s 194us/sample - loss: 0.4802 - acc: 0.7300 - val_loss: 0.5292 - val_acc: 0.6400
Epoch 105/200
100/100 [==============================] - 0s 211us/sample - loss: 0.4762 - acc: 0.6900 - val_loss: 0.5258 - val_acc: 0.9200
Epoch 106/200
100/100 [==============================] - 0s 201us/sample - loss: 0.4724 - acc: 0.8900 - val_loss: 0.5337 - val_acc: 0.6400
Epoch 107/200
100/100 [==============================] - 0s 210us/sample - loss: 0.4732 - acc: 0.6800 - val_loss: 0.5247 - val_acc: 0.7600
Epoch 108/200
100/100 [==============================] - 0s 196us/sample - loss: 0.4728 - acc: 0.8600 - val_loss: 0.5241 - val_acc: 0.6800
Epoch 109/200
100/100 [==============================] - 0s 221us/sample - loss: 0.4713 - acc: 0.8100 - val_loss: 0.5269 - val_acc: 0.6400
Epoch 110/200
100/100 [==============================] - 0s 211us/sample - loss: 0.4777 - acc: 0.6800 - val_loss: 0.5246 - val_acc: 0.6400
Epoch 111/200
100/100 [==============================] - 0s 225us/sample - loss: 0.4674 - acc: 0.6800 - val_loss: 0.5207 - val_acc: 0.6400
Epoch 112/200
100/100 [==============================] - 0s 209us/sample - loss: 0.4647 - acc: 0.6900 - val_loss: 0.5130 - val_acc: 0.7200
Epoch 113/200
100/100 [==============================] - 0s 213us/sample - loss: 0.4655 - acc: 0.8400 - val_loss: 0.5128 - val_acc: 0.9600
Epoch 114/200
100/100 [==============================] - 0s 242us/sample - loss: 0.4615 - acc: 0.9300 - val_loss: 0.5124 - val_acc: 0.9200
Epoch 115/200
100/100 [==============================] - 0s 199us/sample - loss: 0.4633 - acc: 0.9300 - val_loss: 0.5176 - val_acc: 0.6400
Epoch 116/200
100/100 [==============================] - 0s 215us/sample - loss: 0.4599 - acc: 0.6900 - val_loss: 0.5081 - val_acc: 0.8600
Epoch 117/200
100/100 [==============================] - 0s 192us/sample - loss: 0.4598 - acc: 0.7800 - val_loss: 0.5181 - val_acc: 0.6400
Epoch 118/200
100/100 [==============================] - 0s 216us/sample - loss: 0.4641 - acc: 0.7100 - val_loss: 0.5293 - val_acc: 0.6400
Epoch 119/200
100/100 [==============================] - 0s 192us/sample - loss: 0.4646 - acc: 0.6800 - val_loss: 0.5086 - val_acc: 0.6400
Epoch 120/200
100/100 [==============================] - 0s 218us/sample - loss: 0.4527 - acc: 0.6900 - val_loss: 0.5087 - val_acc: 0.7600
Epoch 121/200
100/100 [==============================] - 0s 361us/sample - loss: 0.4599 - acc: 0.8900 - val_loss: 0.5080 - val_acc: 0.7600
Epoch 122/200
100/100 [==============================] - 0s 191us/sample - loss: 0.4559 - acc: 0.8800 - val_loss: 0.5142 - val_acc: 0.6400
Epoch 123/200
100/100 [==============================] - 0s 238us/sample - loss: 0.4612 - acc: 0.7400 - val_loss: 0.5298 - val_acc: 0.6400
Epoch 124/200
100/100 [==============================] - 0s 217us/sample - loss: 0.4618 - acc: 0.6800 - val_loss: 0.5043 - val_acc: 0.6400
Epoch 125/200
100/100 [==============================] - 0s 277us/sample - loss: 0.4507 - acc: 0.7000 - val_loss: 0.4975 - val_acc: 0.8000
Epoch 126/200
100/100 [==============================] - 0s 250us/sample - loss: 0.4453 - acc: 0.8200 - val_loss: 0.4994 - val_acc: 0.6600
Epoch 127/200
100/100 [==============================] - 0s 233us/sample - loss: 0.4464 - acc: 0.7300 - val_loss: 0.5241 - val_acc: 0.6400
Epoch 128/200
100/100 [==============================] - 0s 219us/sample - loss: 0.4572 - acc: 0.6800 - val_loss: 0.4938 - val_acc: 0.9600
Epoch 129/200
100/100 [==============================] - 0s 213us/sample - loss: 0.4451 - acc: 0.9200 - val_loss: 0.5193 - val_acc: 0.6400
Epoch 130/200
100/100 [==============================] - 0s 255us/sample - loss: 0.4654 - acc: 0.6800 - val_loss: 0.5047 - val_acc: 0.6400
Epoch 131/200
100/100 [==============================] - 0s 230us/sample - loss: 0.4440 - acc: 0.6800 - val_loss: 0.4903 - val_acc: 0.8600
Epoch 132/200
100/100 [==============================] - 0s 264us/sample - loss: 0.4385 - acc: 0.8300 - val_loss: 0.5010 - val_acc: 0.6400
Epoch 133/200
100/100 [==============================] - 0s 231us/sample - loss: 0.4463 - acc: 0.8700 - val_loss: 0.4926 - val_acc: 0.8400
Epoch 134/200
100/100 [==============================] - 0s 222us/sample - loss: 0.4482 - acc: 0.9200 - val_loss: 0.4872 - val_acc: 0.8000
Epoch 135/200
100/100 [==============================] - 0s 214us/sample - loss: 0.4373 - acc: 0.7700 - val_loss: 0.4911 - val_acc: 0.8200
Epoch 136/200
100/100 [==============================] - 0s 208us/sample - loss: 0.4399 - acc: 0.9500 - val_loss: 0.5054 - val_acc: 0.6400
Epoch 137/200
100/100 [==============================] - 0s 207us/sample - loss: 0.4520 - acc: 0.8200 - val_loss: 0.4822 - val_acc: 0.8600
Epoch 138/200
100/100 [==============================] - 0s 198us/sample - loss: 0.4338 - acc: 0.8200 - val_loss: 0.4933 - val_acc: 0.6800
Epoch 139/200
100/100 [==============================] - 0s 200us/sample - loss: 0.4439 - acc: 0.8700 - val_loss: 0.4809 - val_acc: 1.0000
Epoch 140/200
100/100 [==============================] - 0s 199us/sample - loss: 0.4348 - acc: 0.9600 - val_loss: 0.4789 - val_acc: 0.8800
Epoch 141/200
100/100 [==============================] - 0s 228us/sample - loss: 0.4305 - acc: 0.9000 - val_loss: 0.4868 - val_acc: 0.6600
Epoch 142/200
100/100 [==============================] - 0s 242us/sample - loss: 0.4338 - acc: 0.7100 - val_loss: 0.4765 - val_acc: 0.9400
Epoch 143/200
100/100 [==============================] - 0s 209us/sample - loss: 0.4258 - acc: 0.9600 - val_loss: 0.4845 - val_acc: 0.6600
Epoch 144/200
100/100 [==============================] - 0s 207us/sample - loss: 0.4285 - acc: 0.7500 - val_loss: 0.4880 - val_acc: 0.6600
Epoch 145/200

### Model Prediction

In [296]:
model.predict(X_test)

array([[0.0070964 , 0.42534918, 0.5675545 ],
       [0.02109862, 0.4930267 , 0.48587465],
       [0.95229745, 0.04307787, 0.0046247 ],
       [0.02403436, 0.5062848 , 0.46968088],
       [0.00719629, 0.4027993 , 0.5900044 ],
       [0.83974093, 0.13664341, 0.02361562],
       [0.03065607, 0.55730265, 0.41204122],
       [0.0379925 , 0.54041326, 0.42159417],
       [0.91847664, 0.07226035, 0.00926301],
       [0.04800338, 0.5632862 , 0.38871047],
       [0.01636266, 0.5056939 , 0.47794342],
       [0.04029114, 0.53937674, 0.42033213],
       [0.9710118 , 0.02672295, 0.00226521],
       [0.00215683, 0.35363838, 0.6442048 ],
       [0.9506299 , 0.04475385, 0.00461625],
       [0.01472945, 0.47059742, 0.5146731 ],
       [0.00210521, 0.3721101 , 0.62578464],
       [0.00539348, 0.42247972, 0.5721268 ],
       [0.94971335, 0.0455059 , 0.00478075],
       [0.92213464, 0.06941833, 0.00844705],
       [0.0780825 , 0.5756609 , 0.3462566 ],
       [0.0031218 , 0.37730134, 0.6195768 ],
       [0.02406936, 0.52630174, 0.44962892],
       [0.00594986, 0.43228695, 0.56176317],
       [0.00631768, 0.466197  , 0.5274853 ],
       [0.01294628, 0.46555224, 0.5215014 ],
       [0.05596106, 0.57321286, 0.37082604],
       [0.06546937, 0.56833875, 0.36619183],
       [0.00431648, 0.386545  , 0.60913855],
       [0.00258357, 0.3556758 , 0.6417407 ],
       [0.01216436, 0.4674619 , 0.5203737 ],
       [0.1519396 , 0.5766831 , 0.2713773 ],
       [0.96877193, 0.02847781, 0.00275025],
       [0.00625402, 0.43054792, 0.5631981 ],
       [0.063064  , 0.58231395, 0.35462204],
       [0.9076569 , 0.08121363, 0.01112947],
       [0.9666208 , 0.03069711, 0.00268209],
       [0.9444518 , 0.05007151, 0.00547666],
       [0.9473992 , 0.0474176 , 0.00518319],
       [0.00263118, 0.38208714, 0.61528164],
       [0.00387532, 0.39508653, 0.6010381 ],
       [0.02883276, 0.556369  , 0.41479817],
       [0.00198849, 0.3417923 , 0.65621924],
       [0.00522764, 0.42331085, 0.5714615 ],
       [0.05948984, 0.5663801 , 0.37413007],
       [0.9405012 , 0.05347815, 0.00602068],
       [0.0688447 , 0.5878059 , 0.34334937],
       [0.05955032, 0.5842592 , 0.35619047],
       [0.00456501, 0.40668094, 0.58875406],
       [0.8993359 , 0.08834233, 0.01232173]], dtype=float32)

### Save the Model

In [0]:
model.save('iris_final.h5')

### Build and Train a Deep Neural network with 2 hidden layer  - Optional - For Practice

Does it perform better than Linear Classifier? What could be the reason for difference in performance?