The purpose of the case study is to classify a given silhouette as one of four different types of vehicle, using a set of features extracted from the silhouette. The vehicle may be viewed from one of many different angles.
Four &quot;Corgie&quot; model vehicles were used for the experiment: 
a double decker bus, 
Cheverolet 
van, 
Saab 9000  
Opel Manta 400 cars. 


This particular combination of vehicles was chosen with the expectation that the bus, van and either one of the cars would be readily distinguishable, but it would be more difficult to distinguish between the cars. The purpose is to classify a given silhouette as one of three types of vehicle, using a set of features extracted from the silhouette. The vehicle may be viewed from one of many different angles.

In [8]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


from sklearn.decomposition import PCA
from scipy.stats import zscore

# 1. Use a new Python notebook and read the data set. Data pre-processing - Understand the data and treat missing values (Use box plot), outliers (5 points)

In [11]:
# Read the dataset
df = pd.read_csv("/Users/boseankit/Desktop/AIML/Assignments/Unsupervised Learning_R5_Project2/vehicle.csv")

In [12]:
df.head()

,compactness,circularity,distance_circularity,radius_ratio,pr.axis_aspect_ratio,max.length_aspect_ratio,scatter_ratio,elongatedness,pr.axis_rectangularity,max.length_rectangularity,scaled_variance,scaled_variance.1,scaled_radius_of_gyration,scaled_radius_of_gyration.1,skewness_about,skewness_about.1,skewness_about.2,hollows_ratio,class
0,95,48.0,83.0,178.0,72.0,10,162.0,42.0,20.0,159,176.0,379.0,184.0,70.0,6.0,16.0,187.0,197,van
1,91,41.0,84.0,141.0,57.0,9,149.0,45.0,19.0,143,170.0,330.0,158.0,72.0,9.0,14.0,189.0,199,van
2,104,50.0,106.0,209.0,66.0,10,207.0,32.0,23.0,158,223.0,635.0,220.0,73.0,14.0,9.0,188.0,196,car
3,93,41.0,82.0,159.0,63.0,9,144.0,46.0,19.0,143,160.0,309.0,127.0,63.0,6.0,10.0,199.0,207,van
4,85,44.0,70.0,205.0,103.0,52,149.0,45.0,19.0,144,241.0,325.0,188.0,127.0,9.0,11.0,180.0,183,bus

In [14]:
df.describe()

,compactness,circularity,distance_circularity,radius_ratio,pr.axis_aspect_ratio,max.length_aspect_ratio,scatter_ratio,elongatedness,pr.axis_rectangularity,max.length_rectangularity,scaled_variance,scaled_variance.1,scaled_radius_of_gyration,scaled_radius_of_gyration.1,skewness_about,skewness_about.1,skewness_about.2,hollows_ratio
count,846.000000,841.000000,842.000000,840.000000,844.000000,846.000000,845.000000,845.000000,843.000000,846.000000,843.000000,844.000000,844.000000,842.000000,840.000000,845.000000,845.000000,846.000000
mean,93.678487,44.828775,82.110451,168.888095,61.678910,8.567376,168.901775,40.933728,20.582444,147.998818,188.631079,439.494076,174.709716,72.447743,6.364286,12.602367,188.919527,195.632388
std,8.234474,6.152172,15.778292,33.520198,7.891463,4.601217,33.214848,7.816186,2.592933,14.515652,31.411004,176.666903,32.584808,7.486190,4.920649,8.936081,6.155809,7.438797
min,73.000000,33.000000,40.000000,104.000000,47.000000,2.000000,112.000000,26.000000,17.000000,118.000000,130.000000,184.000000,109.000000,59.000000,0.000000,0.000000,176.000000,181.000000
25%,87.000000,40.000000,70.000000,141.000000,57.000000,7.000000,147.000000,33.000000,19.000000,137.000000,167.000000,318.000000,149.000000,67.000000,2.000000,5.000000,184.000000,190.250000
50%,93.000000,44.000000,80.000000,167.000000,61.000000,8.000000,157.000000,43.000000,20.000000,146.000000,179.000000,363.500000,173.500000,71.500000,6.000000,11.000000,188.000000,197.000000
75%,100.000000,49.000000,98.000000,195.000000,65.000000,10.000000,198.000000,46.000000,23.000000,159.000000,217.000000,587.000000,198.000000,75.000000,9.000000,19.000000,193.000000,201.000000
max,119.000000,59.000000,112.000000,333.000000,138.000000,55.000000,265.000000,61.000000,29.000000,188.000000,320.000000,1018.000000,268.000000,135.000000,22.000000,41.000000,206.000000,211.000000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 846 entries, 0 to 845
Data columns (total 19 columns):
compactness                    846 non-null int64
circularity                    841 non-null float64
distance_circularity           842 non-null float64
radius_ratio                   840 non-null float64
pr.axis_aspect_ratio           844 non-null float64
max.length_aspect_ratio        846 non-null int64
scatter_ratio                  845 non-null float64
elongatedness                  845 non-null float64
pr.axis_rectangularity         843 non-null float64
max.length_rectangularity      846 non-null int64
scaled_variance                843 non-null float64
scaled_variance.1              844 non-null float64
scaled_radius_of_gyration      844 non-null float64
scaled_radius_of_gyration.1    842 non-null float64
skewness_about                 840 non-null float64
skewness_about.1               845 non-null float64
skewness_about.2               845 non-null float64
hollows_ratio                  846 non-null int64
class                          846 non-null object
dtypes: float64(14), int64(4), object(1)
memory usage: 125.7+ KB

In [48]:
df.iloc[:,0:18]

,compactness,circularity,distance_circularity,radius_ratio,pr.axis_aspect_ratio,max.length_aspect_ratio,scatter_ratio,elongatedness,pr.axis_rectangularity,max.length_rectangularity,scaled_variance,scaled_variance.1,scaled_radius_of_gyration,scaled_radius_of_gyration.1,skewness_about,skewness_about.1,skewness_about.2,hollows_ratio
0,95,48.0,83.0,178.0,72.0,10,162.0,42.0,20.0,159,176.0,379.0,184.0,70.0,6.0,16.0,187.0,197
1,91,41.0,84.0,141.0,57.0,9,149.0,45.0,19.0,143,170.0,330.0,158.0,72.0,9.0,14.0,189.0,199
2,104,50.0,106.0,209.0,66.0,10,207.0,32.0,23.0,158,223.0,635.0,220.0,73.0,14.0,9.0,188.0,196
3,93,41.0,82.0,159.0,63.0,9,144.0,46.0,19.0,143,160.0,309.0,127.0,63.0,6.0,10.0,199.0,207
4,85,44.0,70.0,205.0,103.0,52,149.0,45.0,19.0,144,241.0,325.0,188.0,127.0,9.0,11.0,180.0,183
5,107,NaN,106.0,172.0,50.0,6,255.0,26.0,28.0,169,280.0,957.0,264.0,85.0,5.0,9.0,181.0,183
6,97,43.0,73.0,173.0,65.0,6,153.0,42.0,19.0,143,176.0,361.0,172.0,66.0,13.0,1.0,200.0,204
7,90,43.0,66.0,157.0,65.0,9,137.0,48.0,18.0,146,162.0,281.0,164.0,67.0,3.0,3.0,193.0,202
8,86,34.0,62.0,140.0,61.0,7,122.0,54.0,17.0,127,141.0,223.0,112.0,64.0,2.0,14.0,200.0,208
9,93,44.0,98.0,NaN,62.0,11,183.0,36.0,22.0,146,202.0,505.0,152.0,64.0,4.0,14.0,195.0,204
10,86,36.0,70.0,143.0,61.0,9,133.0,50.0,18.0,130,153.0,266.0,127.0,66.0,2.0,10.0,194.0,202
11,90,34.0,66.0,136.0,55.0,6,123.0,54.0,17.0,118,148.0,224.0,118.0,65.0,5.0,26.0,196.0,202
12,88,46.0,74.0,171.0,68.0,6,152.0,43.0,19.0,148,180.0,349.0,192.0,71.0,5.0,11.0,189.0,195
13,89,42.0,85.0,144.0,58.0,10,152.0,44.0,19.0,144,173.0,345.0,161.0,72.0,8.0,13.0,187.0,197
14,94,49.0,79.0,203.0,71.0,5,174.0,37.0,21.0,154,196.0,465.0,206.0,71.0,6.0,2.0,197.0,199
15,96,55.0,103.0,201.0,65.0,9,204.0,32.0,23.0,166,227.0,624.0,246.0,74.0,6.0,2.0,186.0,194
16,89,36.0,51.0,109.0,52.0,6,118.0,57.0,17.0,129,137.0,206.0,125.0,80.0,2.0,14.0,181.0,185
17,99,41.0,77.0,197.0,69.0,6,177.0,36.0,21.0,139,202.0,485.0,151.0,72.0,4.0,10.0,198.0,199
18,104,54.0,100.0,186.0,61.0,10,216.0,31.0,24.0,173,225.0,686.0,220.0,74.0,5.0,11.0,185.0,195
19,101,56.0,100.0,215.0,NaN,10,208.0,32.0,24.0,169,227.0,651.0,223.0,74.0,6.0,5.0,186.0,193
20,84,47.0,75.0,153.0,64.0,6,154.0,43.0,19.0,145,175.0,354.0,184.0,75.0,0.0,3.0,185.0,192
21,84,37.0,53.0,121.0,59.0,5,123.0,55.0,17.0,125,141.0,221.0,133.0,82.0,7.0,1.0,179.0,183
22,94,43.0,64.0,173.0,69.0,7,150.0,43.0,19.0,142,169.0,344.0,177.0,68.0,9.0,1.0,199.0,206
23,87,39.0,70.0,148.0,61.0,7,143.0,46.0,18.0,136,164.0,307.0,141.0,69.0,1.0,2.0,192.0,199
24,99,53.0,105.0,219.0,66.0,11,204.0,32.0,23.0,165,221.0,623.0,224.0,68.0,0.0,6.0,191.0,201
25,85,45.0,80.0,154.0,64.0,9,147.0,45.0,19.0,148,169.0,324.0,174.0,71.0,1.0,4.0,188.0,199
26,83,36.0,54.0,119.0,57.0,6,128.0,53.0,18.0,125,143.0,238.0,139.0,82.0,6.0,3.0,179.0,183
27,107,54.0,98.0,203.0,65.0,11,218.0,31.0,25.0,167,229.0,696.0,216.0,72.0,1.0,28.0,187.0,199
28,102,45.0,85.0,193.0,64.0,6,192.0,33.0,22.0,146,217.0,570.0,163.0,76.0,6.0,7.0,195.0,193
29,80,38.0,63.0,129.0,55.0,7,146.0,46.0,19.0,130,168.0,314.0,158.0,83.0,9.0,20.0,180.0,185
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
816,90,48.0,85.0,157.0,64.0,11,161.0,43.0,20.0,167,175.0,375.0,186.0,74.0,3.0,16.0,185.0,195
817,104,53.0,108.0,204.0,64.0,11,220.0,31.0,25.0,172,226.0,707.0,203.0,71.0,14.0,30.0,189.0,203
818,95,43.0,96.0,202.0,65.0,10,189.0,35.0,22.0,143,217.0,534.0,166.0,71.0,6.0,27.0,190.0,197
819,93,42.0,98.0,192.0,63.0,9,185.0,36.0,22.0,138,206.0,508.0,173.0,70.0,10.0,21.0,189.0,197
820,87,38.0,71.0,123.0,53.0,8,137.0,49.0,18.0,127,158.0,277.0,145.0,75.0,0.0,9.0,181.0,186
821,104,56.0,96.0,231.0,74.0,11,220.0,30.0,25.0,172,223.0,713.0,218.0,73.0,6.0,16.0,186.0,195
822,95,41.0,82.0,170.0,65.0,9,145.0,46.0,19.0,145,163.0,314.0,140.0,64.0,4.0,8.0,199.0,207
823,105,54.0,105.0,213.0,67.0,10,200.0,33.0,23.0,163,214.0,597.0,214.0,68.0,10.0,20.0,190.0,198
824,106,55.0,96.0,196.0,60.0,12,221.0,30.0,25.0,173,225.0,717.0,214.0,72.0,9.0,13.0,186.0,196
825,86,39.0,84.0,149.0,57.0,8,156.0,43.0,20.0,133,185.0,358.0,157.0,74.0,0.0,23.0,183.0,190
826,95,49.0,92.0,193.0,62.0,10,178.0,37.0,21.0,154,200.0,478.0,171.0,64.0,2.0,0.0,198.0,206
827,99,57.0,100.0,177.0,54.0,13,224.0,30.0,25.0,188,223.0,726.0,213.0,72.0,4.0,7.0,185.0,198
828,89,42.0,66.0,125.0,53.0,7,131.0,51.0,18.0,144,162.0,254.0,162.0,73.0,10.0,17.0,188.0,191
829,95,49.0,82.0,139.0,56.0,11,159.0,43.0,20.0,162,173.0,365.0,185.0,75.0,7.0,10.0,182.0,191
830,97,37.0,70.0,173.0,66.0,7,151.0,43.0,19.0,129,167.0,346.0,119.0,65.0,0.0,16.0,201.0,208
831,100,47.0,70.0,185.0,70.0,7,162.0,40.0,20.0,153,179.0,406.0,172.0,68.0,9.0,6.0,200.0,205
832,108,49.0,109.0,204.0,61.0,11,212.0,31.0,24.0,159,229.0,665.0,215.0,71.0,16.0,11.0,190.0,199
833,92,46.0,83.0,154.0,56.0,6,160.0,41.0,20.0,148,185.0,382.0,184.0,71.0,10.0,5.0,186.0,191
834,82,36.0,51.0,114.0,53.0,4,135.0,50.0,18.0,126,150.0,268.0,144.0,86.0,15.0,4.0,181.0,182
835,111,58.0,105.0,183.0,51.0,6,265.0,26.0,29.0,174,285.0,1018.0,255.0,85.0,4.0,8.0,181.0,183
836,87,45.0,66.0,139.0,58.0,8,140.0,47.0,18.0,148,168.0,294.0,175.0,73.0,3.0,12.0,188.0,196
837,94,46.0,77.0,169.0,60.0,8,158.0,42.0,20.0,148,181.0,373.0,181.0,67.0,12.0,2.0,193.0,199
838,95,43.0,76.0,142.0,57.0,10,151.0,44.0,19.0,149,173.0,339.0,159.0,71.0,2.0,23.0,187.0,200
839,90,44.0,72.0,157.0,64.0,8,137.0,48.0,18.0,144,159.0,283.0,171.0,65.0,9.0,4.0,196.0,203
840,93,34.0,66.0,140.0,56.0,7,130.0,51.0,18.0,120,151.0,251.0,114.0,62.0,5.0,29.0,201.0,207
841,93,39.0,87.0,183.0,64.0,8,169.0,40.0,20.0,134,200.0,422.0,149.0,72.0,7.0,25.0,188.0,195
842,89,46.0,84.0,163.0,66.0,11,159.0,43.0,20.0,159,173.0,368.0,176.0,72.0,1.0,20.0,186.0,197
843,106,54.0,101.0,222.0,67.0,12,222.0,30.0,25.0,173,228.0,721.0,200.0,70.0,3.0,4.0,187.0,201
844,86,36.0,78.0,146.0,58.0,7,135.0,50.0,18.0,124,155.0,270.0,148.0,66.0,0.0,25.0,190.0,195
845,85,36.0,66.0,123.0,55.0,5,120.0,56.0,17.0,128,140.0,212.0,131.0,73.0,1.0,18.0,186.0,190

In [78]:
# mark zero values as missing or NaN
df = df.replace(0, numpy.NaN)
# count the number of NaN values in each column
print(numpy.isnan(df).sum())

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

/Applications/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

ValueError: could not convert string to float: 'van'

In [60]:
# Split the wine data into separate training (70%) and test (30%) sets and then standardize it to unit variance:
X = df.iloc[:,0:18]
y = df.iloc[:,18]

In [73]:
imputer = Imputer()
Xt = imputer.fit_transform(X)

/Applications/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

NameError: name 'datatype' is not defined

In [65]:
import numpy
X = X.replace(0, numpy.NaN)
# count the number of NaN values in each column
print(X.isnull().sum())

compactness                     0
circularity                     5
distance_circularity            4
radius_ratio                    6
pr.axis_aspect_ratio            2
max.length_aspect_ratio         0
scatter_ratio                   1
elongatedness                   1
pr.axis_rectangularity          3
max.length_rectangularity       0
scaled_variance                 3
scaled_variance.1               2
scaled_radius_of_gyration       2
scaled_radius_of_gyration.1     4
skewness_about                 83
skewness_about.1               31
skewness_about.2                1
hollows_ratio                   0
dtype: int64

In [55]:
#Handling Missing data 

from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN',strategy = 'mean',axis = 0)
imputer = imputer.fit(X)
X = imputer.transform(X)

/Applications/anaconda3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)

In [59]:
x.describe()

NameError: name 'x' is not defined

# 2. Understanding the attributes - Find relationship between different attributes (Independent variables) and choose carefully which all attributes have to be a part of the analysis and why (5 points)

# 3. Use PCA from scikit learn and elbow plot to find out reduced number of dimension (which covers more than 95% of the variance) - 10 points

# 4. Use Support vector machines and use grid search (try C values - 0.01, 0.05, 0.5, 1 and kernel = linear, rbf) and find out the best hyper parameters and do cross validation to find the accuracy. (10 points)